### PR TITLE
fix(dnstwist): update dictionaries download URL. Closes #3155

### LINKED ISSUE #3155: Fix DNSTwist dictionaries
The analyzer DNSTwist is broken as of now for this error:

`unable to open /opt/deploy/dnstwist-dictionaries/abused_tlds.dict (no such file or directory)"`

The problem is that we didn't update the URL of the dictionaries that the tool must use in the repo_downloader.sh file.
Now we have this: 

`svn export https://github.com/elceef/dnstwist/tags/20230402/dictionaries dnstwist-dictionaries`

but that URL doesn't exist anymore.

Instead, we should download the dictionaries from this section of the github repo: https://github.com/elceef/dnstwist/tree/master/dictionaries
and ensure that the default option "abuse_tlds.dict" it works as intended

### PR DESCRIPTION
**Pull request by Jay-Dosi**
Closes #3155

## Description

This PR fixes the DNSTwist analyzer failure caused by an obsolete dictionaries
download URL in `repo_downloader.sh`.

The previous URL pointed to a removed upstream tag, which resulted in the
`abused_tlds.dict` file not being downloaded and caused the analyzer to fail
at runtime.

The downloader has been updated to fetch the dictionaries from the current
DNSTwist upstream repository, restoring the expected default behavior without
changing analyzer logic.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read and understood the rules about how to Contribute to this project
- [x] The pull request is for the branch `develop`

- [ ] A new plugin (analyzer, connector, visualizer, playbook, pivot or ingestor) was added or changed
- [ ] I have inserted the copyright banner at the start of the file
- [x] Please avoid adding new libraries as requirements whenever it is possible
- [ ] Linters (Black, Flake, Isort) gave 0 errors
- [ ] I have added tests for the feature/bug I solved
- [ ] If the GUI has been modified, I have provided screenshots and frontend tests

## Testing

- Verified the fix by running DNSTwist on a local IntelOwl Docker setup.
- Confirmed that the analyzer completes successfully using the updated
  dictionaries download source.
- Screenshot and raw JSON output from a successful analysis are provided below.

## Screenshot
image

## JSON
{
  "report": [
    {
      "dns_a": [
        "104.18.26.120"
      ],
      "dns_mx": [
        ""
      ],
      "dns_ns": [
        "elliott.ns.cloudflare.com"
      ],
      "domain": "example.com",
      "fuzzer": "*original"
    },
    {
      "dns_a": [
        "103.168.172.37"
      ],
      "dns_mx": [
        "in1-smtp.messagingengine.com"
      ],
      "dns_ns": [
        "ns1.messagingengine.com"
      ],
      "domain": "exampler.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "104.21.23.31"
      ],
      "dns_ns": [
        "irena.ns.cloudflare.com"
      ],
      "domain": "example8.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "104.21.44.49"
      ],
      "dns_mx": [
        "mx1-hosting.jellyfish.systems"
      ],
      "dns_ns": [
        "dimitris.ns.cloudflare.com"
      ],
      "domain": "example2.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "104.21.59.130"
      ],
      "dns_ns": [
        "keira.ns.cloudflare.com"
      ],
      "domain": "example6.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "104.21.85.141"
      ],
      "dns_mx": [
        "route1.mx.cloudflare.net"
      ],
      "dns_ns": [
        "brady.ns.cloudflare.com"
      ],
      "domain": "examplex.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "104.26.14.194"
      ],
      "dns_ns": [
        "dan.ns.cloudflare.com"
      ],
      "domain": "example3.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "13.223.25.84"
      ],
      "dns_ns": [
        "nsg1.namebrightdns.com"
      ],
      "domain": "example5.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "13.223.25.84"
      ],
      "dns_ns": [
        "domain-for-sale.hugedomainsdns.com"
      ],
      "domain": "examplea.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "13.223.25.84"
      ],
      "dns_ns": [
        "ns1.namebrightdns.com"
      ],
      "domain": "exampleb.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "13.223.25.84"
      ],
      "dns_ns": [
        "domain-for-sale.hugedomainsdns.com"
      ],
      "domain": "examplec.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "13.248.169.48"
      ],
      "dns_ns": [
        "ns1.namefind.com"
      ],
      "domain": "examplez.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "13.248.213.45"
      ],
      "dns_ns": [
        "ns75.domaincontrol.com"
      ],
      "domain": "example9.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "15.197.148.33"
      ],
      "dns_mx": [
        "mailstore1.secureserver.net"
      ],
      "dns_ns": [
        "ns23.domaincontrol.com"
      ],
      "domain": "examplet.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "162.159.130.6"
      ],
      "dns_ns": [
        "ns1.worldnic.com"
      ],
      "domain": "examplek.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "162.248.211.18"
      ],
      "dns_ns": [
        "a.share-dns.com"
      ],
      "domain": "examplee.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "188.40.59.208"
      ],
      "dns_mx": [
        "mail.examplel.com"
      ],
      "dns_ns": [
        "b.ns14.net"
      ],
      "domain": "examplel.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "192.185.44.208"
      ],
      "dns_mx": [
        "mail.example1.com"
      ],
      "dns_ns": [
        "ns8159.hostgator.com"
      ],
      "domain": "example1.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "192.241.217.167"
      ],
      "dns_ns": [
        "ns1.slicehost.net"
      ],
      "domain": "exampleq.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "199.59.243.228"
      ],
      "dns_ns": [
        "curitiba.ns.porkbun.com"
      ],
      "domain": "exampley.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "34.54.3.56"
      ],
      "dns_mx": [
        "alt1.aspmx.l.google.com"
      ],
      "dns_ns": [
        "ns-cloud-b1.googledomains.com"
      ],
      "domain": "examples.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "35.212.120.76"
      ],
      "dns_mx": [
        "mx10.antispam.mailspamprotection.com"
      ],
      "dns_ns": [
        "ns1.siteground.net"
      ],
      "domain": "example7.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "43.252.42.21"
      ],
      "dns_mx": [
        "mx.zoho.com"
      ],
      "dns_ns": [
        "ns6.timway.com"
      ],
      "domain": "exampleg.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "64.190.63.222"
      ],
      "dns_mx": [
        "localhost"
      ],
      "dns_ns": [
        "ns1.sedoparking.com"
      ],
      "domain": "exampled.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "91.98.25.171"
      ],
      "dns_ns": [
        "keira.ns.cloudflare.com"
      ],
      "domain": "example4.com",
      "fuzzer": "addition"
    },
    {
      "dns_ns": [
        "simon.ns.cloudflare.com"
      ],
      "domain": "example0.com",
      "fuzzer": "addition"
    },
    {
      "dns_a": [
        "103.224.182.238"
      ],
      "dns_mx": [
        "park-mx.above.com"
      ],
      "dns_ns": [
        "ns1.abovedomains.com"
      ],
      "domain": "axample.com",
      "fuzzer": "bitsquatting"
    },
    {
      "dns_a": [
        "13.223.25.84"
      ],
      "dns_ns": [
        "nsg1.namebrightdns.com"
      ],
      "domain": "ezample.com",
      "fuzzer": "bitsquatting"
    },
    {
      "dns_a": [
        "13.248.169.48"
      ],
      "dns_ns": [
        "ns1.namefind.com"
      ],
      "domain": "exampla.com",
      "fuzzer": "bitsquatting"
    },
    {
      "dns_a": [
        "13.248.169.48"
      ],
      "dns_mx": [
        ""
      ],
      "dns_ns": [
        "ns1.afternic.com"
      ],
      "domain": "eximple.com",
      "fuzzer": "bitsquatting"
    },
    {
      "dns_a": [
        "15.197.225.128"
      ],
      "dns_ns": [
        "ns33.domaincontrol.com"
      ],
      "domain": "exemple.com",
      "fuzzer": "bitsquatting"
    },
    {
      "dns_a": [
        "50.3.7.113"
      ],
      "dns_ns": [
        "n1.xundns.com"
      ],
      "domain": "uxample.com",
      "fuzzer": "bitsquatting"
    },
    {
      "dns_a": [
        "78.31.70.110"
      ],
      "dns_ns": [
        "ns01.bruechner.net"
      ],
      "domain": "mxample.com",
      "fuzzer": "bitsquatting"
    },
    {
      "dns_ns": [
        "grace.dnspod.net"
      ],
      "domain": "excmple.com",
      "fuzzer": "bitsquatting"
    },
    {
      "dns_a": [
        "104.21.75.90"
      ],
      "dns_ns": [
        "gwen.ns.cloudflare.com"
      ],
      "domain": "exanp1e.com",
      "fuzzer": "homoglyph"
    },
    {
      "dns_a": [
        "13.223.25.84"
      ],
      "dns_ns": [
        "nsg1.namebrightdns.com"
      ],
      "domain": "exammple.com",
      "fuzzer": "homoglyph"
    },
    {
      "dns_a": [
        "13.248.169.48"
      ],
      "dns_mx": [
        ""
      ],
      "dns_ns": [
        "ns1.afternic.com"
      ],
      "domain": "exampic.com",
      "fuzzer": "homoglyph"
    },
    {
      "dns_a": [
        "13.248.169.48"
      ],
      "dns_mx": [
        ""
      ],
      "dns_ns": [
        "ns1.afternic.com"
      ],
      "domain": "exampie.com",
      "fuzzer": "homoglyph"
    },
    {
      "dns_a": [
        "13.248.169.48"
      ],
      "dns_mx": [
        ""
      ],
      "dns_ns": [
        "ns1.afternic.com"
      ],
      "domain": "exanple.com",
      "fuzzer": "homoglyph"
    },
    {
      "dns_a": [
        "144.126.215.83"
      ],
      "dns_ns": [
        "a.secondary2.com"
      ],
      "domain": "xn--xample-9ua.com",
      "fuzzer": "homoglyph"
    },
    {
      "dns_a": [
        "154.195.84.178"
      ],
      "dns_ns": [
        "ns1.taoa.com"
      ],
      "domain": "examplc.com",
      "fuzzer": "homoglyph"
    },
    {
      "dns_a": [
        "216.198.79.1"
      ],
      "dns_mx": [
        "mail.protonmail.ch"
      ],
      "dns_ns": [
        "ns1.vercel-dns.com"
      ],
      "domain": "xn--exampl-gva.com",
      "fuzzer": "homoglyph"
    },
    {
      "dns_a": [
        "38.38.218.4"
      ],
      "dns_ns": [
        "a.share-dns.com"
      ],
      "domain": "exarnple.com",
      "fuzzer": "homoglyph"
    },
    {
      "dns_a": [
        "85.13.149.201"
      ],
      "dns_mx": [
        "w010823c.kasserver.com"
      ],
      "dns_ns": [
        "ns5.kasserver.com"
      ],
      "domain": "xn--exmple-cua.com",
      "fuzzer": "homoglyph"
    },
    {
      "dns_mx": [
        "mxa.examp1e.com"
      ],
      "dns_ns": [
        "osdn.services.net"
      ],
      "domain": "examp1e.com",
      "fuzzer": "homoglyph"
    },
    {
      "dns_ns": [
        "ns-1030.awsdns-00.org"
      ],
      "domain": "exannple.com",
      "fuzzer": "homoglyph"
    },
    {
      "dns_mx": [
        "route1.mx.cloudflare.net"
      ],
      "dns_ns": [
        "andy.ns.cloudflare.com"
      ],
      "domain": "xn--xample-h4a.com",
      "fuzzer": "homoglyph"
    },
    {
      "dns_ns": [
        "andy.ns.cloudflare.com"
      ],
      "domain": "xn--xample-o3a.com",
      "fuzzer": "homoglyph"
    },
    {
      "dns_ns": [
        "andy.ns.cloudflare.com"
      ],
      "domain": "xn--xample-ova.com",
      "fuzzer": "homoglyph"
    },
    {
      "dns_a": [
        "104.21.32.188"
      ],
      "dns_mx": [
        "route1.mx.cloudflare.net"
      ],
      "dns_ns": [
        "apollo.ns.cloudflare.com"
      ],
      "domain": "ex-ample.com",
      "fuzzer": "hyphenation"
    },
    {
      "dns_a": [
        "104.21.9.2"
      ],
      "dns_ns": [
        "dawn.ns.cloudflare.com"
      ],
      "domain": "e-xample.com",
      "fuzzer": "hyphenation"
    },
    {
      "dns_a": [
        "172.233.219.123"
      ],
      "dns_mx": [
        "mail.hope-mail.com"
      ],
      "dns_ns": [
        "ns4.dnsauthority.com"
      ],
      "domain": "examp-le.com",
      "fuzzer": "hyphenation"
    },
    {
      "dns_a": [
        "103.224.182.241"
      ],
      "dns_mx": [
        "park-mx.above.com"
      ],
      "dns_ns": [
        "ns3.abovedomains.com"
      ],
      "domain": "excample.com",
      "fuzzer": "insertion"
    },
    {
      "dns_a": [
        "103.51.63.160"
      ],
      "dns_ns": [
        "ara.ns.cloudflare.com"
      ],
      "domain": "exapmple.com",
      "fuzzer": "insertion"
    },
    {
      "dns_a": [
        "104.21.25.153"
      ],
      "dns_ns": [
        "eric.ns.cloudflare.com"
      ],
      "domain": "examplle.com",
      "fuzzer": "insertion"
    },
    {
      "dns_a": [
        "13.248.169.48"
      ],
      "dns_mx": [
        ""
      ],
      "dns_ns": [
        "ns1.afternic.com"
      ],
      "domain": "4example.com",
      "fuzzer": "insertion"
    },
    {
      "dns_a": [
        "13.248.169.48"
      ],
      "dns_ns": [
        "ns1.namefind.com"
      ],
      "domain": "exsample.com",
      "fuzzer": "insertion"
    },
    {
      "dns_a": [
        "13.248.169.48"
      ],
      "dns_mx": [
        ""
      ],
      "dns_ns": [
        "ns1.afternic.com"
      ],
      "domain": "sexample.com",
      "fuzzer": "insertion"
    },
    {
      "dns_a": [
        "15.197.148.33"
      ],
      "dns_ns": [
        "ns03.domaincontrol.com"
      ],
      "domain": "exampole.com",
      "fuzzer": "insertion"
    },
    {
      "dns_a": [
        "15.197.148.33"
      ],
      "dns_ns": [
        "ns19.domaincontrol.com"
      ],
      "domain": "exampple.com",
      "fuzzer": "insertion"
    },
    {
      "dns_a": [
        "151.80.23.108"
      ],
      "dns_mx": [
        "mx1.mail.ovh.net"
      ],
      "dns_ns": [
        "dns19.ovh.net"
      ],
      "domain": "wexample.com",
      "fuzzer": "insertion"
    },
    {
      "dns_a": [
        "156.235.224.133"
      ],
      "dns_ns": [
        "ns1.taoa.com"
      ],
      "domain": "exzample.com",
      "fuzzer": "insertion"
    },
    {
      "dns_mx": [
        "kr1-aspmx1.worksmobile.com"
      ],
      "dns_ns": [
        "ns.gabia.co.kr"
      ],
      "domain": "examlple.com",
      "fuzzer": "insertion"
    },
    {
      "dns_a": [
        "13.248.169.48"
      ],
      "dns_ns": [
        "ns1.namefind.com"
      ],
      "domain": "eample.com",
      "fuzzer": "omission"
    },
    {
      "dns_a": [
        "139.162.174.209"
      ],
      "dns_mx": [
        "mail.mailerhost.net"
      ],
      "dns_ns": [
        "baobao.ns.giantpanda.com"
      ],
      "domain": "exampe.com",
      "fuzzer": "omission"
    },
    {
      "dns_a": [
        "185.53.178.99"
      ],
      "dns_ns": [
        "ns1.parkingcrew.net"
      ],
      "domain": "exaple.com",
      "fuzzer": "omission"
    },
    {
      "dns_a": [
        "23.227.38.65"
      ],
      "dns_mx": [
        "alt1.aspmx.l.google.com"
      ],
      "dns_ns": [
        "ns13.domaincontrol.com"
      ],
      "domain": "xample.com",
      "fuzzer": "omission"
    },
    {
      "dns_a": [
        "67.210.233.131"
      ],
      "dns_mx": [
        "localhost.exmple.com"
      ],
      "dns_ns": [
        "ns19.globalcon.net"
      ],
      "domain": "exmple.com",
      "fuzzer": "omission"
    },
    {
      "dns_a": [
        "77.247.183.149"
      ],
      "dns_ns": [
        "ns1.milesmx.com"
      ],
      "domain": "examle.com",
      "fuzzer": "omission"
    },
    {
      "dns_a": [
        "104.21.10.82"
      ],
      "dns_mx": [
        "_dc-mx.302032b7a870.exxample.com"
      ],
      "dns_ns": [
        "cesar.ns.cloudflare.com"
      ],
      "domain": "exxample.com",
      "fuzzer": "repetition"
    },
    {
      "dns_a": [
        "96.38.240.54"
      ],
      "dns_mx": [
        "mail.onlineearth.com"
      ],
      "dns_ns": [
        "ns1.onlineearth.com"
      ],
      "domain": "eexample.com",
      "fuzzer": "repetition"
    },
    {
      "dns_mx": [
        "mx01.spamx.net"
      ],
      "dns_ns": [
        "ns1.dyna-ns.net"
      ],
      "domain": "exaample.com",
      "fuzzer": "repetition"
    },
    {
      "dns_a": [
        "103.224.182.244"
      ],
      "dns_mx": [
        "park-mx.above.com"
      ],
      "dns_ns": [
        "ns1.abovedomains.com"
      ],
      "domain": "examplr.com",
      "fuzzer": "replacement"
    },
    {
      "dns_a": [
        "103.224.182.244"
      ],
      "dns_mx": [
        "park-mx.above.com"
      ],
      "dns_ns": [
        "ns1.abovedomains.com"
      ],
      "domain": "examplw.com",
      "fuzzer": "replacement"
    },
    {
      "dns_a": [
        "103.224.212.217"
      ],
      "dns_mx": [
        "park-mx.above.com"
      ],
      "dns_ns": [
        "ns1.abovedomains.com"
      ],
      "domain": "ecample.com",
      "fuzzer": "replacement"
    },
    {
      "dns_a": [
        "104.21.47.159"
      ],
      "dns_ns": [
        "lauryn.ns.cloudflare.com"
      ],
      "domain": "exzmple.com",
      "fuzzer": "replacement"
    },
    {
      "dns_a": [
        "104.21.96.96"
      ],
      "dns_ns": [
        "selah.ns.cloudflare.com"
      ],
      "domain": "edample.com",
      "fuzzer": "replacement"
    },
    {
      "dns_a": [
        "13.223.25.84"
      ],
      "dns_ns": [
        "nsg1.namebrightdns.com"
      ],
      "domain": "4xample.com",
      "fuzzer": "replacement"
    },
    {
      "dns_a": [
        "13.223.25.84"
      ],
      "dns_ns": [
        "nsg1.namebrightdns.com"
      ],
      "domain": "exsmple.com",
      "fuzzer": "replacement"
    },
    {
      "dns_a": [
        "13.223.25.84"
      ],
      "dns_ns": [
        "nsg1.namebrightdns.com"
      ],
      "domain": "rxample.com",
      "fuzzer": "replacement"
    },
    {
      "dns_a": [
        "139.162.174.209"
      ],
      "dns_mx": [
        "mail.mailerhost.net"
      ],
      "dns_ns": [
        "baobao.ns.giantpanda.com"
      ],
      "domain": "examole.com",
      "fuzzer": "replacement"
    },
    {
      "dns_a": [
        "139.162.174.209"
      ],
      "dns_mx": [
        "mail.mailerhost.net"
      ],
      "dns_ns": [
        "baobao.ns.giantpanda.com"
      ],
      "domain": "wxample.com",
      "fuzzer": "replacement"
    },
    {
      "dns_a": [
        "156.244.167.176"
      ],
      "dns_ns": [
        "ns1.taoa.com"
      ],
      "domain": "exampke.com",
      "fuzzer": "replacement"
    },
    {
      "dns_a": [
        "200.69.18.139"
      ],
      "dns_mx": [
        "mail.exampl3.com"
      ],
      "dns_ns": [
        "ns-cloud-a1.googledomains.com"
      ],
      "domain": "exampl3.com",
      "fuzzer": "replacement"
    },
    {
      "dns_a": [
        "208.91.197.27"
      ],
      "dns_ns": [
        "ns95.worldnic.com"
      ],
      "domain": "exapple.com",
      "fuzzer": "replacement"
    },
    {
      "dns_a": [
        "45.130.41.12"
      ],
      "dns_mx": [
        "esample.com"
      ],
      "dns_ns": [
        "ns1.inmotionhosting.com"
      ],
      "domain": "esample.com",
      "fuzzer": "replacement"
    },
    {
      "dns_ns": [
        "etta.ns.cloudflare.com"
      ],
      "domain": "exampls.com",
      "fuzzer": "replacement"
    },
    {
      "dns_ns": [
        "ns-cloud-d1.googledomains.com"
      ],
      "domain": "examplz.com",
      "fuzzer": "replacement"
    },
    {
      "dns_a": [
        "209.38.54.191"
      ],
      "domain": "exam.ple.com",
      "fuzzer": "subdomain"
    },
    {
      "dns_a": [
        "103.224.182.243"
      ],
      "dns_mx": [
        "park-mx.above.com"
      ],
      "dns_ns": [
        "ns1.abovedomains.com"
      ],
      "domain": "exapmle.com",
      "fuzzer": "transposition"
    },
    {
      "dns_a": [
        "104.18.74.230"
      ],
      "dns_mx": [
        "amir.mx.cloudflare.net"
      ],
      "dns_ns": [
        "ara.ns.cloudflare.com"
      ],
      "domain": "exmaple.com",
      "fuzzer": "transposition"
    },
    {
      "dns_a": [
        "13.223.25.84"
      ],
      "dns_ns": [
        "nsg1.namebrightdns.com"
      ],
      "domain": "examlpe.com",
      "fuzzer": "transposition"
    },
    {
      "dns_a": [
        "157.7.236.66"
      ],
      "dns_mx": [
        "mail1.eaxmple.com"
      ],
      "dns_ns": [
        "dns1.eaxmple.com"
      ],
      "domain": "eaxmple.com",
      "fuzzer": "transposition"
    },
    {
      "dns_a": [
        "192.64.151.235"
      ],
      "dns_mx": [
        "mail.computer.com"
      ],
      "dns_ns": [
        "ns1.anydns.com"
      ],
      "domain": "exampel.com",
      "fuzzer": "transposition"
    },
    {
      "dns_mx": [
        "mx.xeample.com"
      ],
      "dns_ns": [
        "delta.netnautics.net"
      ],
      "domain": "xeample.com",
      "fuzzer": "transposition"
    },
    {
      "dns_a": [
        "13.223.25.84"
      ],
      "dns_ns": [
        "nsg1.namebrightdns.com"
      ],
      "domain": "examplecom.com",
      "fuzzer": "various"
    },
    {
      "dns_a": [
        "13.223.25.84"
      ],
      "dns_ns": [
        "nsg1.namebrightdns.com"
      ],
      "domain": "examplo.com",
      "fuzzer": "vowel-swap"
    },
    {
      "dns_a": [
        "13.248.169.48"
      ],
      "dns_mx": [
        ""
      ],
      "dns_ns": [
        "ns1.afternic.com"
      ],
      "domain": "ixample.com",
      "fuzzer": "vowel-swap"
    },
    {
      "dns_a": [
        "15.197.148.33"
      ],
      "dns_ns": [
        "ns55.domaincontrol.com"
      ],
      "domain": "oxample.com",
      "fuzzer": "vowel-swap"
    },
    {
      "dns_a": [
        "198.185.159.145"
      ],
      "dns_ns": [
        "ns-cloud-e1.googledomains.com"
      ],
      "domain": "exampli.com",
      "fuzzer": "vowel-swap"
    }
  ],
  "data_model": null,
  "errors": [],
  "parameters": {
    "mxcheck": true,
    "tld_dict": "",
    "fuzzy_hash": "ssdeep",
    "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.34",
    "nameservers": "",
    "language_dict": "",
    "fuzzy_hash_url": ""
  }
}

### CODE REVIEW

**Comment by mlodic** [comment]
you need follow the PR guidelines and the template before asking for a review

**Comment by Jay-Dosi** [comment]
Template updated as requested. Ready for review.

**Comment by mlodic** [comment]
you must read it, there's requested to open the PR against the develop branch, last time I ask this again

**Comment by Jay-Dosi** [comment]
I am really sorry for that. Now, the PR updated to target the `develop` branch and template filled accordingly. Ready for review.

File: api_app/analyzers_manager/repo_downloader.sh [hunk 1]
```diff
@@ -18,7 +18,20 @@ chown -R www-data:www-data ~/.quark-engine
 
 # Clone dictionaries for dnstwist analyzer
 cd /opt/deploy || exit
-svn export https://github.com/elceef/dnstwist/tags/20230402/dictionaries dnstwist-dictionaries
+
+#changing this url
+#svn export https://github.com/elceef/dnstwist/tags/20230402/dictionaries dnstwist-dictionaries
+#fix: Download DNSTwist dictionaries from upstream repository
```
Comment (mlodic) [inline api_app/analyzers_manager/repo_downloader.sh]: no need to keep commented the old changed here

**Comment by Jay-Dosi** [comment]
I have made the changes as you directed.
