### PR TITLE
fix(frontend): update guide targets and add artifacts step. Closes #3343

### LINKED ISSUE #3343: The Guide does not work as intended anymore
Image
This Guide button should be available the first times that IntelOwl is used. It is not working anymore as intended, most probably because some pages changed over time and the references are wrong. Also, the "artifact" section is new and should be mentioned

### PR DESCRIPTION
**Pull request by berardifra**
# Description
This PR fixes the broken `react-joyride` Guide in the frontend. Several UI components have evolved over time causing the Guide to break as it tried to attach to outdated or non-existent selectors.
Specifically, this PR:
1. Fixes the broken `target` selectors for `Analyzers`, `pluginconfigbutton`, and `investigations`.
2. Adds a missing step for the **Artifacts** page, including assigning the proper `id="artifacts"` to its NavItem in `AppHeader.jsx`.
3. Updates the text descriptions for the "Plugins" and "Scan Page" steps to reflect the current UI state.
## Type of change
- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
# Checklist
- [x] I have read and understood the rules about [how to Contribute](https://intelowlproject.github.io/docs/IntelOwl/contribute/) to this project
- [x] The pull request is for the branch `develop`
- [ ] A new plugin (analyzer, connector, visualizer, playbook, pivot or ingestor) was added or changed, in which case:
    - [ ] ...
- [ ] I have inserted the copyright banner at the start of the file: ```# This file is a part of IntelOwl https://github.com/intelowlproject/IntelOwl # See the file 'LICENSE' for copying permission.```
- [ ] Please avoid adding new libraries as requirements whenever it is possible.
- [ ] If external libraries/packages with restrictive licenses were added, they were added in the Legal Notice section.
- [x] Linters (`Ruff`/`Eslint`/`Prettier`) gave 0 errors. If you have correctly installed [pre-commit](https://intelowlproject.github.io/docs/IntelOwl/contribute/#how-to-start-setup-project-and-development-instance), it does these checks and adjustments on your behalf.
- [x] I have added tests for the feature/bug I solved (see `tests` folder). All the tests (new and old ones) gave 0 errors.
- [x] If the GUI has been modified:
    - [x] I have a provided a screenshot of the result in the PR.
    - [ ] I have created new frontend tests for the new component or updated existing ones.
- [x] After you had submitted the PR, if `DeepSource`, `Django Doctors` or other third-party linters have triggered any alerts during the CI checks, I have solved those alerts.

### CODE REVIEW

**Comment by berardifra** [comment]
**Note for reviewers:** @mlodic 

While testing the Guide flow to fix the missing selectors and add the *Artifacts* step, I also came across two additional bugs that broke the UX of the Guide, which I have proactively fixed in this PR:

1. **Tooltip Overlap UX Bug:** The Guide tooltips were previously hiding behind sticky `DataTable` headers (like the columns in the Plugins page). I fixed this by slightly bumping the `zIndex` in `GuideWrapper.jsx`'s `styles.options` to `10000`, ensuring the Guide is always correctly displayed on top of the UI.
*Before:*
bug


2. **History Page URL Crash:** Transitioning from Step 6 (Scan page) to Step 7 (History page) previously navigated blindly to `/history/jobs`. This caused a frontend crash (`invalid date` React Error) since the `History.jsx` component expects date query parameters (e.g. `received_request_time__gte`) to be present in order to render the table. I fixed this by navigating to `/history` instead, allowing the router's `CustomRedirect` to safely inject the latest 7-day default time-range before blindly showing the job table.
*Before:*
error


*Everything correctly working now.*
bug_resolved

**Comment by berardifra** [comment]
Hey @mlodic sorry, I forgot to add the screen recordings for "Guide" and "Artifcats" page to display correctly. Should I add them or is this ok? Thanks.

**Comment by mlodic** [comment]
since you did the effort, this would certainly help having a thorough understanding of the changes

File: frontend/src/components/GuideWrapper.jsx [hunk 1]
```diff
@@ -63,8 +62,8 @@ export default function GuideWrapper() {
         <div id="guidebox">
           <h3>Scan Page</h3>
           <p>
-            You could get started with analyzing various observables with just
-            three steps{" "}
+            You can get started analyzing observables or files here by filling
+            out the form and running your selected playbooks.
```
Comment (mlodic) [inline frontend/src/components/GuideWrapper.jsx]:
```suggestion
            out the form and running either the playbook of your choice or single analyzers indipendently.
```

File: frontend/package-lock.json [hunk 2]
```diff
@@ -1,12 +1,12 @@
 {
   "name": "intelowl",
-  "version": "6.4.0",
```
Comment (mlodic) [inline frontend/package-lock.json:3]: changes in the package-lock are unrealted and most probably caused by running npm install locally. please remove

File: frontend/src/components/GuideWrapper.jsx [hunk 3]
```diff
@@ -141,6 +140,19 @@ export default function GuideWrapper() {
...
       disableBeacon: true,
     },
+    {
+      target: "#artifacts",
+      content: (
+        <div id="guidebox">
+          <h3>Artifacts</h3>
+          <p>
+            Explore organization artifacts like yara rules, signatures, and
+            threat rules
```
Comment (mlodic) [inline frontend/src/components/GuideWrapper.jsx]: I would change the sentence here to replicate the one that we have in the docs
"""
An artifact is the representation of an observable or a file, and is therefore a unique object that can be analyzed multiple times for different evaluations.
"""

**Comment by berardifra** [comment]
All good now, thanks for clarification @mlodic 

test
